taskname: '+ mambaconv SSD'    #'+ MoConv2 SSD'
common:
  run_label: "train"
  accum_freq: 1
  accum_after_epoch: -1
  log_freq: 500
  auto_resume: true
  mixed_precision: true
dataset:
  root_train: "/home/xuwei/Project/PyTorch/Important_projects/classification/imagenet_v1/COCO"
  root_val: "/home/xuwei/Project/PyTorch/Important_projects/classification/imagenet_v1/COCO"  #"/mnt/vision_datasets/coco"
  name: "coco_ssd"
  category: "detection"
  train_batch_size0: 64     #64   # effective batch size is 128 (32 * 4 GPUs)
  val_batch_size0: 64    #64
  eval_batch_size0: 1
  workers: 8
  persistent_workers: false
  pin_memory: true
image_augmentation:
  resize:
    enable: true
    size: [320, 320]
    interpolation: "bicubic"
sampler:
  name: "batch_sampler"
  bs:
    crop_size_width: 320
    crop_size_height: 320
loss:
  category: "detection"
  detection:
    name: "ssd_multibox_loss"
    ssd_multibox_loss:
      neg_pos_ratio: 3
optim:
  name: "adamw"
  weight_decay: 0.01
  no_decay_bn_filter_bias: false
  adamw:
    beta1: 0.9
    beta2: 0.999
scheduler:
  name: "cosine"
  is_iteration_based: false
  max_epochs: 200
  warmup_iterations: 500
  warmup_init_lr: 0.00009
  cosine:
    max_lr: 0.001  #0.0009      # s 0.001
    min_lr: 1.5e-5   #1.0e-6     # s 1.2e-5
anchor_generator:
  name: "ssd"
  ssd:
    output_strides: [ 16, 32, 64, 128, 256, -1 ]
    aspect_ratios: [ [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [2] ]
    min_scale_ratio: 0.1
    max_scale_ratio: 1.05
matcher:
  name: "ssd"
  ssd:
    center_variance: 0.1             #0.1
    size_variance: 0.2               #0.2
    iou_threshold: 0.5               #0.5
model:
  detection:
    name: "ssd"
    ssd:
      proj_channels: [512, 256, 256, 128, 128, 64]
      nms_iou_threshold: 0.5                       # original 0.5
  classification:
    name: "mambaconv"        # moconv
    classifier_dropout: 0.1                         #0.1
    mit:
      mode: "mamba13"              #mamba13   mamba_n    mamba_t
      ffn_dropout: 0.0
      attn_dropout: 0.0
      dropout: 0.1
      number_heads: 4
      no_fuse_local_global_features: false
      conv_kernel_size: 3
    activation:
      name: "swish"
    pretrained: "/home/xuwei/Project/PyTorch/Important_projects/classification/imagenet_v1/cvnets-mamba/classification_results/train/mamba-s/checkpoint_ema_score_78.9320.pt"
  normalization:
    name: "sync_batch_norm"
    momentum: 0.1
  activation:
    name: "relu"
    inplace: false
  layer:
    global_pool: "mean"
    conv_init: "kaiming_normal"
    linear_init: "normal"
ema:
  enable: true
  momentum: 0.00015
stats:
  val: [ "loss", "coco_map"]
  train: ["loss"]
  checkpoint_metric: "coco_map.bbox"
  checkpoint_metric_max: true
